### ISSUE TITLE
Make localhost port configurable

### ISSUE THREAD

**Issue by michaelbaudino** [guillaumebriday/switch-to-localhost#1]
This is an awesome extension :sparkles: 

It would be even more awesome to be able to configure default port (rather than using 3000) :raised_hands:

**Comment by guillaumebriday** [comment]
![Screenshot 2020-07-20 at 14 01 27](https://user-images.githubusercontent.com/8252238/87935664-cc9aff00-ca91-11ea-85da-ddc0df9f19fb.png)

It will be coming in the next 1.1 version ! I'm waiting for approval.
